//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CLRESUS.rc
//
#define IDS_LANGUAGE                    1
#define IDS_DEPENDINFO                  2
#define IDS_TABMOREOPTIONS              2
#define IDC_BTRETRY                     3
#define IDS_SELECTINFO                  3
#define ID_BTAPPLY                      3
#define IDS_RUNTIMEINJECTION            3
#define IDS_ADDPROGRAM                  4
#define IDS_CMDRESTORELFN               5
#define IDS_TITRESTORELFN               6
#define IDS_TABGENERAL                  7
#define IDS_TABOPTIONS                  8
#define IDS_TABDEPEND                   9
#define IDS_TABHELP                     10
#define IDS_ADVANCED                    11
#define IDS_MBLINK                      12
#define IDS_HLPCONTENT                  13
#define IDS_CHMFILE                     13
#define IDS_CTXMENU                     14
#define IDS_CTXMENUHELP                 15
#define IDS_ERRFILENOTFOUND             16
#define IDS_LDRNAME                     17
#define IDS_LDRDESC                     18
#define IDS_ERR_NOTEXEFILE              19
#define IDS_ERR1                        20
#define IDS_EMAILLINK                   21
#define IDS_LANGMENU                    22
#define IDS_PROGRAMFILTER               23
#define IDS_COLUMNNAME                  24
#define IDS_COLUMNDIR                   25
#define IDS_COLUMNDATETIME              26
#define IDS_MANAGERTITLE                27
#define IDS_HLPMANAGER                  28
#define IDS_HLPCONFIG                   29
#define IDS_CREDITS                     30
#define IDS_DELREGSETTINGS              31
#define IDS_VERSION                     32
#define IDS_REALDATE                    32
#define IDS_DLGFONT                     33
#define IDS_CREATIONDATE                34
#define IDS_COLUMNTIMEZONE              34
#define IDS_MODIFICATIONDATE            35
#define IDS_SYSTEMTIMEZONE              35
#define IDS_CUSTOMDATE                  36
#define IDS_SYSTEMWIDEACTIVATED         36
#define IDS_REALTIME                    37
#define IDS_SYSTEMWIDEDEACTIVATED       37
#define IDS_CREATIONTIME                38
#define IDS_SHORTCUTSUFFIX              38
#define IDS_MODIFICATIONTIME            39
#define IDS_PROGRAMNAME                 39
#define IDS_CUSTOMTIME                  40
#define IDS_PATH                        40
#define IDS_REALTIMEZONE                41
#define IDS_STATICINJECTION             41
#define IDS_DEFAULT                     42
#define IDS_FLASHDRIVE                  43
#define IDS_CUSTOM                      44
#define IDS_SETTINGSPERMISSIONERROR     45
#define IDM_PROGRAM                     102
#define IDD_ABOUT                       102
#define IDM_POPUP                       103
#define IDD_CONFIG                      104
#define IDM_LOADPRESET                  104
#define IDD_SETTINGS                    107
#define IDD_TABMOREOPTIONS              116
#define IDD_TABDEPEND                   124
#define IDD_RETRY                       143
#define IDD_TABOPTIONS                  152
#define IDD_TABHELP                     153
#define IDD_TABGENERAL                  154
#define IDD_PROPEXT                     156
#define IDC_EDTM0                       701
#define IDC_EDTM1                       702
#define IDC_EDTM2                       703
#define IDC_EDYEAR                      706
#define IDC_SEPTIME1                    707
#define IDC_SEPTIME0                    708
#define IDC_SPINAMPM                    709
#define IDC_LSTAMPM                     710
#define IDC_CALENDAR                    711
#define IDC_CLOCK                       712
#define IDC_CMBMONTH                    713
#define IDC_SPINYEAR                    714
#define IDC_TITLE                       1001
#define IDC_GRPSTATIC                   1002
#define IDC_VERSIONINFO                 1003
#define IDC_BUILDINFO                   1004
#define IDC_LSTFILE                     1005
#define IDC_LSTWINSYSFILE               1006
#define IDC_LSTGRAYCHK                  1007
#define IDC_LSTUNCHK                    1008
#define IDC_LEGEND                      1008
#define IDC_LSTCHK                      1009
#define IDC_LSTAPPEXE                   1010
#define IDC_CHKTIME                     1011
#define IDC_CMBTIMEZONE                 1012
#define IDC_RADRUNTIMEINJEC             1012
#define IDC_CHKDATE                     1013
#define IDC_RADSTATICINJEC              1013
#define IDC_CHKTZ                       1014
#define IDC_LSTDEPEND                   1022
#define IDC_CHKSWI_APPINIT              1024
#define IDC_LNKCREATESHORTCUT           1025
#define IDC_CHKSHELLEXT                 1025
#define IDC_RUNTIMEINFO                 1026
#define IDC_CHKSWI_CULOGON              1026
#define IDC_CHKSWI_LMLOGON              1027
#define IDC_GRPADMIN                    1028
#define IDC_GRPRUNTIME                  1029
#define IDC_LINE                        1031
#define IDC_LINE_BOTTOM                 1031
#define IDC_LINE2                       1032
#define IDC_LINE_TOP                    1032
#define IDC_CHKCST                      1033
#define IDC_MAIL_LINK                   1034
#define IDC_RAD_WINREG                  1035
#define IDC_RAD_CLDIR                   1036
#define IDC_RAD_APPDATADIR              1037
#define IDC_CMBPRESET                   1041
#define IDC_CHKESETTINGSINAPPDIR        1042
#define IDC_CHKFORWARDSETTINGSTOLOCAL   1043
#define IDC_CUSTOM1                     1044
#define IDC_LINK                        1045
#define IDC_CMBINJECTIONMODE            1046
#define IDC_EDTCMDPARAM                 1047
#define IDC_EDTCMDLINE                  1048
#define IDC_RADDEFAULT                  1049
#define IDC_RADLOCALSETTINGS            1050
#define IDC_RADCOMPLETELYSTANDALONE     1051
#define IDC_RADSTANDALONE               1052
#define IDC_RADSHARED                   1053
#define IDC_CHKSYS                      1054
#define IDC_CHKACTIVATE                 1055
#define IDC_BTRESTARTLATER              1056
#define IDC_INFO                        1057
#define IDC_BTRESTARTNOW                1058
#define IDC_ICO                         1059
#define IDC_CHKADVANCED                 1060
#define IDC_MB_LINK                     1061
#define IDC_MB_LINK2                    1062
#define IDC_BTLOADPRESETDT              1063
#define IDC_BTHELP                      1064
#define ID_HELP_DOCUMENTATION           40002
#define ID_HELP_ABOUT                   40003
#define ID_PROGRAM_RUN                  40004
#define ID_PUP_CURSYS                   40004
#define ID_PROGRAM_CONFIG               40005
#define ID_LOADFILECREATIONDATE         40005
#define ID_FILEMODIFICATION             40006
#define ID_CURSYS                       40007
#define ID_FILECREATIONDATE             40008
#define ID_PROGRAM_SETTING              40009
#define ID_OPTION_SETTING               40010
#define ID_PROGRAM_DELETE               40011
#define ID_PROGRAM_CLOSE                40012
#define ID_HELP_WEBSITE                 40013
#define ID_VIEW_LARGEICONS              40018
#define ID_VIEW_SMALLICONS              40019
#define ID_VIEW_LISTICONS               40020
#define ID_VIEW_DETAILSICONS            40021
#define ID_VIEW_REFRESH                 40022
#define ID_HELP_LANG_FIRST              45000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        115
#define _APS_NEXT_COMMAND_VALUE         40013
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
